//https://github.com/KELiON/redux-async-initial-state

export default {
  city: 'Ставрополь',
  cityGW: {
    'Ставрополь': 'stavropol',
  },
  //Photo quanty to reduce server requests
  galMap: {
    'Ставрополь': [
      {
        id: 99,
        qty: 100,
        name: 'Фестиваль «Зелёный свет 2018» часть 2',
        date: '02.09.2018',
      },
      {
        id: 98,
        qty: 84,
        name: 'Фестиваль «Зелёный свет 2018»',
        date: '02.09.2018',
      },
      {
        id: 86,
        qty: 130,
        name: 'Фестиваль «Зелёный свет»',
        date: '05.08.2017',
      },
      {
        id: 87,
        qty: 161,
        name: 'Игра «Мой город»',
        date: '24.06.2017',
      },
      {
        id: 83,
        qty: 120,
        name: 'День России',
        date: '12.07.2017',
      },
      {
        id: 79,
        qty: 164,
        name: 'Выставка кошек',
        date: '26.03.2017',
      },
      {
        id: 78,
        qty: 56,
        name: 'День всех влюбленных',
        date: '15.02.2017',
      },
      {
        id: 76,
        qty: 21,
        name: 'Высадка катальпы',
        date: '22.10.2016',
      },
      {
        id: 69,
        qty: 140,
        name: 'Парк Победы',
        date: '04.09.2016',
      },
      {
        id: 60,
        qty: 459,
        name: 'Фестиваль «Зелёный свет»',
        date: '19.06.2016',
      },
      {
        id: 56,
        qty: 288,
        name: 'День Победы',
        date: '09.05.2016',
      },
      {
        id: 55,
        qty: 86,
        name: 'Чемпионат Downhill',
        date: '08.05.2016',
      },
      {
        id: 50,
        qty: 155,
        name: 'Татьянин день',
        date: '27.01.2016',
      },
      {
        id: 47,
        qty: 111,
        name: 'Карлс Джуниор',
        date: '12.09.2015',
      },
      {
        id: 45,
        qty: 127,
        name: 'Wake Weekend',
        date: '15.08.2015',
      },
      {
        id: 41,
        qty: 358,
        name: 'World of tanks',
        date: '19.07.2015',
      },
      {
        id: 30,
        qty: 453,
        name: 'Фестиваль "Зелёный свет"',
        date: '07.06.2015',
      },
      {
        id: 24,
        qty: 159,
        name: 'День Победы',
        date: '09.05.2015',
      },
      {
        id: 18,
        qty: 85,
        name: '1 мая',
        date: '01.05.2015',
      },
      {
        id: 14,
        qty: 248,
        name: 'День города',
        date: '28.09.2014',
      },
      {
        id: 4,
        qty: 216,
        name: 'World of Tanks',
        date: '04.12.2013',
      },
      {
        id: 2,
        qty: 517,
        name: 'День города',
        date: '21.09.2013',
      },
      {
        id: 1,
        qty: 515,
        name: 'Улыбнись :)',
        date: '01.05.2012',
      },
    ],
    'Липецк': [
      {
        id: 84,
        qty: 274,
        name: 'День города',
        date: '16.07.2017',
      },
      {
        id: 75,
        qty: 139,
        name: 'Зелёная точка',
        date: '22.10.2016',
      },
      {
        id: 64,
        qty: 152,
        name: 'День города',
        date: '17.07.2016',
      },
      {
        id: 54,
        qty: 253,
        name: '9 мая',
        date: '09.05.2016',
      },
      {
        id: 46,
        qty: 37,
        name: 'День знаний',
        date: '01.09.2015',
      },
      {
        id: 43,
        qty: 158,
        name: 'Моторшоу',
        date: '08.08.2015',
      },
      {
        id: 40,
        qty: 228,
        name: 'День города',
        date: '18.07.2015',
      },
      {
        id: 35,
        qty: 76,
        name: 'День Молодежи',
        date: '27.06.2015',
      },
      {
        id: 31,
        qty: 105,
        name: 'День России',
        date: '12.06.2015',
      },
      {
        id: 29,
        qty: 86,
        name: '31 Мая',
        date: '31.05.2015',
      },
      {
        id: 19,
        qty: 118,
        name: '9 Мая',
        date: '09.05.2015',
      },
    ],
    'Елец': [
      {
        id: 48,
        qty: 39,
        name: 'Зелёный день в клубе Ригель',
        date: '12.09.2015',
      },
      {
        id: 44,
        qty: 60,
        name: 'День Флага',
        date: '22.08.2015',
      },
      {
        id: 37,
        qty: 38,
        name: 'День Молодёжи',
        date: '27.06.2015',
      },
    ],
    'Белгород': [
      {
        id: 20,
        qty: 334,
        name: '9 мая',
        date: '09.05.2015',
      },
      {
        id: 22,
        qty: 51,
        name: 'Авто пробег',
        date: '08.05.2015',
      },
    ],
    'Тамбов': [
      {
        id: 61,
        qty: 1458,
        name: 'Картинг турнир',
        date: '19.06.2016',
      },
      {
        id: 34,
        qty: 393,
        name: 'Колорфест',
        date: '13.06.2015',
      },
      {
        id: 33,
        qty: 150,
        name: 'День Города',
        date: '12.06.2015',
      },
      {
        id: 21,
        qty: 695,
        name: '9 мая',
        date: '09.05.2015',
      },
      {
        id: 15,
        qty: 303,
        name: 'Покровская ярмарка',
        date: '12.10.2014',
      },
      {
        id: 12,
        qty: 441,
        name: 'Фотовыставка «Сушка»',
        date: '28.07.2014',
      },
      {
        id: 9,
        qty: 128,
        name: 'День города',
        date: '12.06.2014',
      },
      {
        id: 8,
        qty: 398,
        name: 'Первый день лета',
        date: '01.06.2014',
      },
      {
        id: 7,
        qty: 584,
        name: 'Выходные с ЗТ',
        date: '08.05.2014',
      },
      {
        id: 5,
        qty: 626,
        name: '1 мая',
        date: '01.05.2014',
      },
    ],
    'Белорецк': [
      {
        id: 68,
        qty: 94,
        name: 'Бизнес-ланч для клиентов',
        date: '30.08.2016',
      },
      {
        id: 65,
        qty: 181,
        name: 'День металлурга Белорецк',
        date: '16.07.2016',
      },
      {
        id: 52,
        qty: 415,
        name: 'Горнолыжные соревнования детей',
        date: '14.02.2016',
      },
      {
        id: 42,
        qty: 267,
        name: 'День города',
        date: '18.07.2015',
      },
    ],
    'Элиста': [
      {
        id: 94,
        qty: 204,
        name: 'Рануралан',
        date: '22.10.2017',
      },
      {
        id: 81,
        qty: 90,
        name: 'Финал "Сокровище Калмыкии 2017"',
        date: '24.06.2017',
      },
      {
        id: 82,
        qty: 183,
        name: 'Цаган Сар',
        date: '27.02.2017',
      },
      {
        id: 73,
        qty: 58,
        name: 'День города Элиста',
        date: '24.09.2016',
      },
      {
        id: 67,
        qty: 96,
        name: 'RUN Уралан Калмыкия 2016',
        date: '21.08.2016',
      },
      {
        id: 57,
        qty: 183,
        name: 'Сокровище Калмыкии 2016',
        date: '26.05.2016',
      },
      {
        id: 53,
        qty: 316,
        name: 'Мисс Интернет 2016',
        date: '06.05.2016',
      },
      {
        id: 51,
        qty: 53,
        name: 'Празднование Цаган Сара',
        date: '09.02.2016',
      },
      {
        id: 49,
        qty: 275,
        name: 'День города',
        date: '19.09.2015',
      },
      {
        id: 28,
        qty: 140,
        name: 'День 1 микрорайона',
        date: '24.05.2015',
      },
      {
        id: 27,
        qty: 37,
        name: '9 мая',
        date: '09.05.2015',
      },
    ],
    'Кочубеевское': [
      {
        id: 92,
        qty: 39,
        name: 'День села Кочубеевское',
        date: '16.09.2017',
      },
    ],
    'Невинномысск': [
      {
        id: 97,
        qty: 82,
        name: 'День семьи, любви и верности',
        date: '08.07.2018',
      },
      {
        id: 96,
        qty: 43,
        name: 'Ярмарка',
        date: '04.11.2017',
      },
      {
        id: 93,
        qty: 52,
        name: 'Давай Зажигай',
        date: '17.09.2017',
      },
      {
        id: 91,
        qty: 49,
        name: 'День города',
        date: '16.09.2017',
      },
      {
        id: 90,
        qty: 33,
        name: 'Огонь знаний',
        date: '05.09.2017',
      },
      {
        id: 85,
        qty: 74,
        name: 'Парад колясок',
        date: '09.07.2017',
      },
      {
        id: 88,
        qty: 81,
        name: 'Фестиваль красок',
        date: '24.06.2017',
      },
      {
        id: 80,
        qty: 82,
        name: 'День победы',
        date: '09.05.2017',
      },
      {
        id: 70,
        qty: 228,
        name: 'Огонь знаний',
        date: '05.09.2016',
      },
      {
        id: 58,
        qty: 100,
        name: 'День защиты детей',
        date: '01.06.2016',
      },
      {
        id: 37,
        qty: 38,
        name: 'Автошок',
        date: '28.06.2015',
      },
      {
        id: 23,
        qty: 90,
        name: '9 Мая',
        date: '09.05.2015',
      },
      {
        id: 17,
        qty: 196,
        name: 'Стань Дедом Морозом',
        date: '18.12.2014',
      },
      {
        id: 16,
        qty: 1102,
        name: 'День города',
        date: '11.10.2014',
      },
      {
        id: 13,
        qty: 388,
        name: 'Пикник',
        date: '30.08.2014',
      },
      {
        id: 11,
        qty: 109,
        name: 'День России',
        date: '12.06.2014',
      },
      {
        id: 10,
        qty: 541,
        name: 'Детский праздник',
        date: '09.06.2014',
      },
      {
        id: 6,
        qty: 580,
        name: 'Автошок',
        date: '04.05.2014',
      },
      {
        id: 3,
        qty: 1382,
        name: 'Открытие офиса',
        date: '17.10.2013',
      },
    ],
    'Томск': [
      {
        id: 71,
        qty: 21,
        name: 'День Маленького Томича',
        date: '11.09.2016',
      },
      {
        id: 26,
        qty: 130,
        name: '16 мая',
        date: '16.05.2015',
      },
    ],
    'Владивосток': [
      {
        id: 77,
        qty: 31,
        name: 'Halloween 2016',
        date: '01.11.2016',
      },
      {
        id: 74,
        qty: 67,
        name: 'Международный Марафон',
        date: '24.09.2016',
      },
      {
        id: 66,
        qty: 103,
        name: 'Микки и Мини Маус',
        date: '30.07.2016',
      },
      {
        id: 63,
        qty: 113,
        name: 'Дети. Миньоны.',
        date: '16.07.2016',
      },
      {
        id: 62,
        qty: 150,
        name: 'Проект "Улыбнись"',
        date: '26.06.2016',
      },
      {
        id: 39,
        qty: 437,
        name: 'День города',
        date: '04.07.2015',
      },
      {
        id: 36,
        qty: 597,
        name: 'День молодежи',
        date: '27.06.2015',
      },
    ],
    'Уфа': [
      {
        id: 95,
        qty: 54,
        name: 'Хэллоуин 2017',
        date: '31.10.2017',
      },
      {
        id: 72,
        qty: 54,
        name: 'Stand Up',
        date: '16.09.2016',
      },
      {
        id: 59,
        qty: 15,
        name: 'День соседа',
        date: '27.06.2016',
      },
      {
        id: 32,
        qty: 2603,
        name: 'День города',
        date: '12.06.2015',
      },
      {
        id: 25,
        qty: 263,
        name: '9 мая',
        date: '09.05.2015',
      },
    ],
  },
  activeGallery: {
    id: 0,
    body: ['0'],
    name: '',
  },
  socials: {
    'Ставрополь': {
      vk: 'zelenaya_net',
      fb: 'zeltochka',
      ok: 'zelenayatochka',
      inst: 'zelenaya_tochka',
      yt: 'zelenayatochka',
    },
    'Липецк': {
      vk: 'ztlip',
      yt: 'zelenayatochka',
    },
    'Белгород': {
      vk: 'zelenaya_net_belgorod',
      yt: 'zelenayatochka',
    },
    'Ефремов': {
      vk: 'ztefr',
      fb: 'zeltochka',
      ok: 'zelenayatochka',
      inst: 'zelenaya_tochka',
      yt: 'zelenayatochka',
    },
    'Нальчик': {
      vk: 'zelenaya_net',
      fb: 'zeltochka',
      ok: 'zelenayatochka',
      inst: 'zelenayatochka',
      yt: 'zelenayatochka',
    },
    'Тамбов': {
      vk: 'zelenaya_net_tambov',
      ok: 'group/53218961588331',
    },
    'Белорецк': {
      vk: 'zelenayaufa',
      yt: 'zelenayatochka',
    },
    'Кочубеевское': {
      vk: 'zelenaya_net',
      fb: 'zelenkatochka',
      ok: 'zelenayatochka',
      inst: 'zelenaya_tochka',
      yt: 'zelenayatochka',
    },
    'Невинномысск': {
      vk: 'zelenaya_net_nevinnomyssk',
      fb: 'zelenkatochka',
      ok: 'nevinka.zelenaya.net',
      inst: 'zelenaya_tochka_nsk',
      yt: 'zelenayatochka',
    },
    'Томск': {
      vk: 'zelenaya_net_tomsk',
      yt: 'zelenayatochka',
    },
    'Владивосток': {
      vk: 'zelenayavl',
      yt: 'zelenayatochka',
    },
    'Нефтекамск': {
      vk: 'zelenayaufa',
      yt: 'zelenayatochka',
    },
    'Уфа': {
      vk: 'zelenayaufa',
      yt: 'zelenayatochka',
    },
    'Елец': {
      vk: 'elets.zelenaya',
      fb: 'zeltochka',
      ok: 'zelenayatochka',
      inst: 'zelenaya_tochka',
      yt: 'zelenayatochka',
    },
    'Москва': {
      vk: 'zelenaya_net',
      fb: 'zeltochka',
      ok: 'zelenayatochka',
      inst: 'zelenaya_tochka',
      yt: 'zelenayatochka',
    },
    'Элиста': {
      vk: 'zelenayaelista',
      yt: 'zelenayatochka',
    },
  },
  banners: {},
}

//
// export default {
//   city: 'Ставрополь',
//   //Photo quanty to reduce server requests
//   galMap: {
//     'Ставрополь': [
//       {
//         id: 79,
//         qty: 50,
//         name: 'Фестиваль «зелёный свет»',
//         date: '07.06.2015',
//       },
//       {
//         id: 81,
//         qty: 70,
//         name: 'test 2',
//         date: '00.00.000',
//       },
//       {
//         id: 80,
//         qty: 60,
//         name: 'test',
//         date: '00.00.000',
//       },
//       {
//         id: 82,
//         qty: 80,
//         name: 'test 3',
//         date: '00.00.000',
//       },
//       {
//         id: 80,
//         qty: 60,
//         name: 'test',
//         date: '00.00.000',
//       },
//       {
//         id: 82,
//         qty: 80,
//         name: 'test 3',
//         date: '00.00.000',
//       },
//       {
//         id: 82,
//         qty: 80,
//         name: 'test 3',
//         date: '00.00.000',
//       },
//       {
//         id: 80,
//         qty: 60,
//         name: 'test',
//         date: '00.00.000',
//       },
//     ],
//     'Липецк': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Елец': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Белгород': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Тамбов': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Белорецк': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Элиста': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Невинномысск': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Томск': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Владивосток': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//     'Уфа': [
//       {
//         id: 83,
//         qty: 50,
//         name: 'Тестовая галерея',
//         date: '07.06.2015',
//       },
//     ],
//   },
//   activeGallery: {
//     id: 0,
//     body: ['0'],
//     name: '',
//   },
//   socials: {
//     'Ставрополь': {
//       vk: 'zelenaya_net',
//       fb: 'zeltochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Липецк': {
//       vk: 'ztlip',
//       yt: 'zelenayatochka',
//     },
//     'Белгород': {
//       vk: 'zelenaya_net_belgorod',
//       yt: 'zelenayatochka',
//     },
//     'Ефремов': {
//       vk: 'ztefr',
//       fb: 'zeltochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Нальчик': {
//       vk: 'zelenaya_net',
//       fb: 'zeltochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenayatochka',
//       yt: 'zelenayatochka',
//     },
//     'Тамбов': {
//       vk: 'zelenaya_net_tambov',
//       ok: 'group/53218961588331',
//     },
//     'Белорецк': {
//       vk: 'zelenayaufa',
//       yt: 'zelenayatochka',
//     },
//     'Кочубеевское': {
//       vk: 'zelenaya_net',
//       fb: 'zelenkatochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Невинномысск': {
//       vk: 'zelenaya_net',
//       fb: 'zelenkatochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Томск': {
//       vk: 'zelenaya_net_tomsk',
//       yt: 'zelenayatochka',
//     },
//     'Владивосток': {
//       vk: 'zelenayavl',
//       yt: 'zelenayatochka',
//     },
//     'Нефтекамск': {
//       vk: 'zelenayaufa',
//       yt: 'zelenayatochka',
//     },
//     'Уфа': {
//       vk: 'zelenayaufa',
//       yt: 'zelenayatochka',
//     },
//     'Елец': {
//       vk: 'elets.zelenaya',
//       fb: 'zeltochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Москва': {
//       vk: 'zelenaya_net',
//       fb: 'zeltochka',
//       ok: 'zelenayatochka',
//       inst: 'zelenaya_tochka',
//       yt: 'zelenayatochka',
//     },
//     'Элиста': {
//       vk: 'zelenayaelista',
//       yt: 'zelenayatochka',
//     },
//   },
//   banners: {},
// }
